name: Build And Test
description: Builds and Tests an application/package

inputs:
  NAME:
    description: The name of the app/package
    required: true
  PACKAGE_NAME:
    description: The name of the package to be published
    required: true
  COVERAGE_PATH:
    description: The path to where the coverage folder would generate
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: Install turbo
      shell: bash
      run: npm i -g turbo
    - name: Generate output
      shell: bash
      run: turbo prune --scope=${{ inputs.PACKAGE_NAME }}
    - name: Install Dependencies
      shell: bash
      working-directory: ./out
      run: npm ci
    - name: Build Package
      shell: bash
      working-directory: ./out
      run: |
        turbo build --filter=${{ inputs.PACKAGE_NAME }}...
    - name: Test
      shell: bash
      working-directory: ./out
      run: |
        turbo test:cov --scope=${{ inputs.PACKAGE_NAME }}
        turbo test:e2e:cov --scope=${{ inputs.PACKAGE_NAME }}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        name: ${{ inputs.PACKAGE_NAME }}
        files: ${{ inputs.COVERAGE_PATH }}/coverage/coverage-final.json
        flags: ${{ inputs.NAME }},unittests
    - name: Upload coverage reports to Codecov [E2E]
      uses: codecov/codecov-action@v3
      with:
        name: ${{ inputs.PACKAGE_NAME }}
        files: ${{ inputs.COVERAGE_PATH }}/coverage-e2e/coverage-final.json
        flags: ${{ inputs.NAME }},e2etests

        