name: Get PR environment name
description: Gets the pr environment name in the format pr-{number}

outputs:
  env_name:
    description: The environment name
    value: ${{ steps.parse_url.outputs.ENV_NAME }}

runs:
  using: composite
  steps:
    - shell: bash
      id: parse_url
      run: |
        pull_request_url=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        if [[ $pull_request_url =~ ([0-9]+$) ]]; then
            parsed_pull_request_number=${BASH_REMATCH[1]}
        else
            echo "unable to parse pr number from pull_request_url"
            exit 1
        fi

        echo "ENV_NAME=pr-$parsed_pull_request_number" >> $GITHUB_OUTPUT
