name: Build And Publish Package
description: Builds and publishes a package for publish

inputs:
  PACKAGE_NAME:
    description: The name of the package to be published
    required: true
  PACKAGE_FOLDER:
    description: The folder that includes the package
    required: true
  GITHUB_TOKEN:
    description: The github token
    required: true
  NPM_TOKEN:
    description: The npm token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install turbo
      shell: bash
      run: npm i -g turbo
    - name: Generate output
      shell: bash
      run: turbo prune --scope="${{ inputs.PACKAGE_NAME }}"
    - name: Install Dependencies
      shell: bash
      working-directory: ./out
      run: npm ci
    - name: Build Package
      shell: bash
      working-directory: ./out
      run: |
        turbo build --filter=${{ inputs.PACKAGE_NAME }}...
    - name: Push Package
      shell: bash
      working-directory: ./out/packages/${{ inputs.PACKAGE_FOLDER }}
      env:
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        npm run release