name: Build multiarch docker
description: Builds a docker image with multiple architectures

inputs:
  IMAGE_NAME:
    description: The image name to publish
    required: true
  WORKING_DIRECTORY:
    description: The working directory
    default: .
  DOCKERFILE_PATH:
    description: The path to the dockerfile
    default: Dockerfile
  PLATFORMS:
    description: The platforms to build for
    default: linux/amd64,linux/arm64
  DOCKER_USERNAME:
    description: The username to publish to docker
    required: true
  DOCKER_PASSWORD:
    description:  The password to publish to docker
    required: true
  DOCKER_REGISTRY:
    description: The docker registry to push to
    default: ghcr.io  

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: |
          ghcr.io/${{ inputs.IMAGE_NAME }}
        tags: |
          type=ref,event=pr
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        # context: ${{ inputs.WORKING_DIRECTORY }}
        file: ${{ inputs.DOCKERFILE_PATH }}
        push: true
        platforms: ${{ inputs.PLATFORMS }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=local,src=${{ inputs.WORKING_DIRECTORY }}