name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BREWBOT_GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm release:canary
        if: github.ref != 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BREWBOT_GITHUB_TOKEN }}
      - run: pnpm release:ci
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BREWBOT_GITHUB_TOKEN }}
