name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.BREWBOT_GITHUB_TOKEN }}
      - name: get-npm-version
        id: bmp-backend-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: apps/backend
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/brewery-management-platform/backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=backend-{{version}}
            type=semver,pattern=backend-{{major}}.{{minor}}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - run: pnpm release:canary
      #   if: github.ref != 'refs/heads/main'
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GH_TOKEN: ${{ secrets.BREWBOT_GITHUB_TOKEN }}
      # - run: pnpm release:ci
      #   if: github.ref == 'refs/heads/main' 
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GH_TOKEN: ${{ secrets.BREWBOT_GITHUB_TOKEN }}
          
      
