name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - run: git fetch --unshallow --tags
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: yarn install --immutable
      - run: yarn build
      - run: |
          git config user.name ota-brewbot
          git config user.email infra@overtheairbrew.com
      - run: yarn release:ci
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
