name: '[APP] Build Backend'

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - id: env-name
        uses: ./.github/actions/get-env-name
      - uses: ./.github/actions/build-app-package
        with:
          PACKAGE_NAME: '@overtheairbrew/backend'
          COVERAGE_PATH: ./out/apps/backend
          NAME: backend
      # - uses: ./.github/actions/build-multi-arch-docker
      #   with:
      #     IMAGE_NAME: overtheairbrew/brewery-management-platform-backend
      #     WORKING_DIRECTORY: ./out
      #     DOCKERFILE_PATH: ./apps/backend/Dockerfile
      #     DOCKER_USERNAME: ${{ github.actor }}
      #     DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
