name: '[PACKAGE] Build Plugins'

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-app-package
        with:
          PACKAGE_NAME: '@overtheairbrew/plugins'
          COVERAGE_PATH: ./out/packages/plugins
          NAME: plugins
