# name: Build backend docker image

# on:
#   push:
#     branches:
#       - main

# env:
#   REGISTRY: ghcr.io

# jobs:
#   check-for-changes:
#     runs-on: ubuntu-latest
#     outputs:
#       hasChanged: steps.check.outputs.changed === 'true'
#     steps:
#       - uses: actions/checkout@v3
#       - name: Check if version has been updated
#         id: check
#         uses: EndBug/version-check@v2
#         with:
#           file-name: apps/backend/package.json
#       - run: echo ${{ steps.check.outputs.changed }}

#   build-docker-image:
#     needs:
#       - check-for-changes
#     runs-on: ubuntu-latest
#     if: needs.check-for-changes.outputs.hasChanged == 'true'
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version-file: .nvmrc

#       - run: npm i -g turbo@1.10.5
#       - uses: pnpm/action-setup@v2
#         name: Install pnpm
#         id: pnpm-install
#         with:
#           version: 8
#       - name: get-npm-version
#         id: package-version
#         uses: martinbeentjes/npm-get-version-action@v1.3.1
#         with:
#           path: apps/backend
#       - run: turbo prune --scope=@overtheairbrew/bmp-backend
#       - run: pnpm install --no-frozen-lockfile && pnpm install
#         working-directory: out
#       - run: pnpm build
#         working-directory: out
#       - name: Log in to the Container registry
#         uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Build and push Docker image
#         uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
#         with:
#           context: .
#           file: apps/backend/Dockerfile
#           push: true
#           tags: |
#             backend-${{ steps.package-version.outputs.current-version }}
#             latest
#           labels: |
#             org.opencontainers.image.source=https://github.com/overtheairbrew/brewery-management-platform
#           platforms: linux/arm64,linux/amd64
#           build-args: |
#             VERSION=${{ steps.package-version.outputs.current-version }}
